// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4en2iZf4bqX-P5OWqpXchLPrWj1fRfs',
    appId: '1:35170445165:web:110d5726a032384ef85c64',
    messagingSenderId: '35170445165',
    projectId: 'fir-c2661',
    authDomain: 'fir-c2661.firebaseapp.com',
    storageBucket: 'fir-c2661.appspot.com',
    measurementId: 'G-ZSNDSKZ4QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBJWat7QlqyahRErm4Ho89PMohZJ5E9I4',
    appId: '1:35170445165:android:cea6307669c97ea7f85c64',
    messagingSenderId: '35170445165',
    projectId: 'fir-c2661',
    storageBucket: 'fir-c2661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrysLKuR21o_Dhy4bLd3_WssA3UWPeN4',
    appId: '1:35170445165:ios:ca231271c4519072f85c64',
    messagingSenderId: '35170445165',
    projectId: 'fir-c2661',
    storageBucket: 'fir-c2661.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvrysLKuR21o_Dhy4bLd3_WssA3UWPeN4',
    appId: '1:35170445165:ios:ca231271c4519072f85c64',
    messagingSenderId: '35170445165',
    projectId: 'fir-c2661',
    storageBucket: 'fir-c2661.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4en2iZf4bqX-P5OWqpXchLPrWj1fRfs',
    appId: '1:35170445165:web:dc6fb2e5384d1008f85c64',
    messagingSenderId: '35170445165',
    projectId: 'fir-c2661',
    authDomain: 'fir-c2661.firebaseapp.com',
    storageBucket: 'fir-c2661.appspot.com',
    measurementId: 'G-9QF1J1MTYL',
  );
}
